# Generated by Django 5.1.7 on 2025-05-06 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('leave_type', models.CharField(choices=[('paid_leave', 'Paid Leave'), ('unpaid_leave', 'Unpaid Leave'), ('roaster_leave', 'Roster Leave')], default='paid_leave', max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others'), ('A', 'All')], default='A', max_length=1)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed'), ('A', 'All')], default='A', max_length=1)),
                ('number_of_days', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('show_on_employee', models.BooleanField(default=True)),
                ('prorata_status', models.BooleanField(default=False)),
                ('encashable_status', models.BooleanField(default=False)),
                ('half_leave_status', models.BooleanField(default=False)),
                ('half_leave_type', models.CharField(choices=[('full_day', 'Full Day'), ('half_day', 'Half Day')], default='full_day', max_length=50)),
                ('carry_forward_status', models.BooleanField(default=False)),
                ('sandwich_rule_status', models.BooleanField(default=False)),
                ('pre_inform_days', models.IntegerField(default=0)),
                ('max_per_day_leave', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('job_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('probation', 'Probation')], default='permanent', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_type_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
