# Generated by Django 5.1.7 on 2025-05-07 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_year', '0002_remove_fiscalyear_end_date_eng_and_more'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='fiscal_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_type_fiscal_year', to='fiscal_year.fiscalyear'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='carry_forward_status',
            field=models.BooleanField(default=False, verbose_name='Enable Carry Forward?'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='encashable_status',
            field=models.BooleanField(default=False, verbose_name='Enable Encashable?'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='half_leave_status',
            field=models.BooleanField(default=False, verbose_name='Enable Half Leave?'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='half_leave_type',
            field=models.CharField(choices=[('first_half', 'First Half'), ('second_half', 'Second Half')], default='first_half', max_length=50),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='job_type',
            field=models.CharField(choices=[('all', 'All'), ('permanent', 'Permanent'), ('contract', 'Contract'), ('probation', 'Probation')], default='all', max_length=50, verbose_name='Job Type'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_type',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('roaster', 'Roster')], default='paid', max_length=50, verbose_name='Leave Type'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='max_per_day_leave',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum number of days per request'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='number_of_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='pre_inform_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Leave request should be submitted before (in days)'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='prorata_status',
            field=models.BooleanField(default=False, verbose_name='Enable Prorata?'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='sandwich_rule_status',
            field=models.BooleanField(default=False, verbose_name='Enable Sandwich Rule?'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='show_on_employee',
            field=models.BooleanField(default=True, verbose_name='Display on Employee?'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active'),
        ),
    ]
