# Generated by Django 5.1.7 on 2025-06-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='show_on_employee',
            field=models.BooleanField(default=True, verbose_name='Display on Team Member?'),
        ),
    ]
