# Generated by Django 5.1.7 on 2025-05-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_alter_leavetype_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='leave_type',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('roaster', 'Roster')], default='paid', max_length=50, verbose_name='Type'),
        ),
    ]
