# Generated by Django 5.1.7 on 2025-05-14 13:14

import django.db.models.deletion
import nepali_datetime_field.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_employeeleave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', nepali_datetime_field.models.NepaliDateField()),
                ('end_date', nepali_datetime_field.models.NepaliDateField()),
                ('no_of_days', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Verified', 'Verified'), ('Declined', 'Declined'), ('Approved', 'Approved')], default='Applied')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_leave', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_type_leaves', to='leave.leavetype')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
