# Generated by Django 5.1.7 on 2025-05-26 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_type_leave', to='leave.leavetype'),
        ),
    ]
