# Generated by Django 5.1.7 on 2025-05-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_alter_leave_leave_type'),
        ('leave', '0007_employeeleave_is_active_alter_leave_leave_type'),
    ]

    operations = [
    ]
