# Generated by Django 5.1.7 on 2025-05-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_merge_20250527_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='job_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('probation', 'Probation'), ('all', 'All')], default='all', max_length=50, verbose_name='Job Type'),
        ),
    ]
