# Generated by Django 5.1.7 on 2025-06-05 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_alter_leave_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_leave_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_leave_leave_type', to='leave.leavetype'),
        ),
    ]
