# Generated by Django 5.1.7 on 2025-06-17 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('department', '0002_branch'),
        ('leave', '0012_alter_leave_end_date_alter_leave_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_type_branch', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_type_department', to='department.department'),
        ),
    ]
