# Generated by Django 5.1.7 on 2025-06-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('department', '0002_branch'),
        ('leave', '0013_leavetype_branch_leavetype_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='department',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='leave_type_branches', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='leave_type_departments', to='department.department'),
        ),
    ]
