# Generated by Django 5.1.7 on 2025-05-05 16:59

import nepali_datetime_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=50)),
                ('start_date', nepali_datetime_field.models.NepaliDateField()),
                ('end_date', nepali_datetime_field.models.NepaliDateField()),
                ('start_date_eng', models.DateField()),
                ('end_date_eng', models.DateField()),
                ('is_active', models.BooleanField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y')),
                ('is_current', models.BooleanField(choices=[('Y', 'Yes'), ('N', 'No')], default='N')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
