# Generated by Django 5.1.7 on 2025-05-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_year', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalyear',
            name='end_date_eng',
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='start_date_eng',
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='is_current',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
