# Generated by Django 5.1.7 on 2025-06-10 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_year', '0003_remove_fiscalyear_is_active_fiscalyear_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
