# Generated by Django 5.1.7 on 2025-06-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_year', '0004_alter_fiscalyear_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='start_date',
            field=models.DateField(),
        ),
    ]
