# Generated by Django 5.1.7 on 2025-06-13 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_year', '0005_alter_fiscalyear_end_date_and_more'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, choices=[(1, 'Baisakh'), (2, 'Jestha'), (3, 'Ashadh'), (4, 'Shrawan'), (5, 'Bhadra'), (6, 'Ashwin'), (7, 'Kartik'), (8, 'Mangsir'), (9, 'Poush'), (10, 'Magh'), (11, 'Falgun'), (12, 'Chaitra')], null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_product', models.PositiveIntegerField()),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('Released', 'Released'), ('On hold', 'On hold'), ('On hold release', 'On hold release')], max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_release_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_release_employee', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_release_fiscal_year', to='fiscal_year.fiscalyear')),
                ('salary_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_release_salary_type', to='payroll.salarytype')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_release_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
