# Generated by Django 5.1.7 on 2025-06-13 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_year', '0005_alter_fiscalyear_end_date_and_more'),
        ('payroll', '0002_salaryrelease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryrelease',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='salaryrelease',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_release_fiscal_year', to='fiscal_year.fiscalyear', verbose_name='Fiscal Year'),
        ),
        migrations.AlterField(
            model_name='salaryrelease',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Net Amount'),
        ),
        migrations.AlterField(
            model_name='salaryrelease',
            name='no_of_product',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='No of Product'),
        ),
        migrations.AlterField(
            model_name='salaryrelease',
            name='salary_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_release_salary_type', to='payroll.salarytype', verbose_name='Salary Type'),
        ),
        migrations.AlterField(
            model_name='salaryrelease',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
