# Generated by Django 5.1.7 on 2025-06-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_alter_salaryrelease_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryrelease',
            name='month',
            field=models.IntegerField(choices=[(1, 'Baisakh'), (2, 'Jestha'), (3, 'Ashadh'), (4, 'Shrawan'), (5, 'Bhadra'), (6, 'Ashwin'), (7, 'Kartik'), (8, 'Mangsir'), (9, 'Poush'), (10, 'Magh'), (11, 'Falgun'), (12, 'Chaitra')], null=True),
        ),
        migrations.AlterField(
            model_name='salaryrelease',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Net Amount'),
        ),
    ]
