# Generated by Django 5.1.7 on 2025-05-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_roster_rosterdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='rosterdetail',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
