# Generated by Django 5.1.7 on 2025-06-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payout Interval',
                'verbose_name_plural': 'Payout Intervals',
            },
        ),
        migrations.CreateModel(
            name='SalaryRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('month', models.IntegerField(choices=[(1, 'Baisakh'), (2, 'Jestha'), (3, 'Ashadh'), (4, 'Shrawan'), (5, 'Bhadra'), (6, 'Ashwin'), (7, 'Kartik'), (8, 'Mangsir'), (9, 'Poush'), (10, 'Magh'), (11, 'Falgun'), (12, 'Chaitra')], null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_product', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='No of Product')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Net Amount')),
                ('status', models.CharField(blank=True, choices=[('Released', 'Released'), ('On hold', 'On hold'), ('On hold release', 'On hold release')], max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salary Type',
                'verbose_name_plural': 'Salary Types',
            },
        ),
    ]
