# Generated by Django 5.1.7 on 2025-06-19 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscal_year', '0001_initial'),
        ('payout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutinterval',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_interval_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryrelease',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_release_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryrelease',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_release_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryrelease',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_release_fiscal_year', to='fiscal_year.fiscalyear', verbose_name='Fiscal Year'),
        ),
        migrations.AddField(
            model_name='salaryrelease',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_release_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salarytype',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_type_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryrelease',
            name='salary_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_release_salary_type', to='payout.salarytype', verbose_name='Salary Type'),
        ),
    ]
