# Generated by Django 5.1.7 on 2025-06-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='assign_overtime',
            field=models.BooleanField(default=False),
        ),
    ]
