# Generated by Django 5.1.7 on 2025-04-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_official_email_alter_authuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Official email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Personal email'),
        ),
    ]
