# Generated by Django 5.1.7 on 2025-06-20 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_province'),
        ('user', '0002_payout_assign_overtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingdetail',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch', to='branch.branch', verbose_name='Substation'),
        ),
    ]
