# Generated by Django 5.1.7 on 2025-06-20 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_district'),
        ('user', '0003_alter_workingdetail_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='issue_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.district', verbose_name='Issuing Authority'),
        ),
    ]
