# Generated by Django 5.1.7 on 2025-04-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_shift_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='shift_id',
            new_name='shift',
        ),
    ]
