# Generated by Django 5.1.7 on 2025-04-25 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
        ('user', '0005_rename_shift_id_profile_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift', to='roster.shift'),
        ),
    ]
