# Generated by Django 5.1.7 on 2025-05-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others'), ('A', 'All')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed'), ('A', 'All')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(choices=[('H', 'Hinduism'), ('B', 'Buddhism'), ('I', 'Islam'), ('K', 'Kirant'), ('C', 'Christianity'), ('O', 'Others'), ('A', 'All')], default='H', max_length=50),
        ),
    ]
