# Generated by Django 5.1.7 on 2025-05-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profile_gender_alter_profile_marital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_type',
            field=models.CharField(choices=[('all', 'All'), ('permanent', 'Permanent'), ('contract', 'Contract'), ('probation', 'Probation')], default='probation', verbose_name='Job Type'),
        ),
    ]
