# Generated by Django 5.1.7 on 2025-05-14 13:07

import nepali_datetime_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profile_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joining_date',
            field=nepali_datetime_field.models.NepaliDateField(blank=True, null=True, verbose_name='Joining Date'),
        ),
    ]
