# Generated by Django 5.1.7 on 2025-05-14 13:08

import nepali_datetime_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='joining_date',
            field=nepali_datetime_field.models.NepaliDateField(null=True, verbose_name='Joining Date'),
        ),
    ]
