# Generated by Django 5.1.7 on 2025-05-26 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
        ('user', '0010_alter_profile_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift', to='roster.shift'),
        ),
    ]
