# Generated by Django 5.1.7 on 2025-05-26 16:51

import django.db.models.deletion
import nepali_datetime_field.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
        ('user', '0011_alter_profile_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shift',
        ),
        migrations.CreateModel(
            name='WorkingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('all', 'All'), ('permanent', 'Permanent'), ('contract', 'Contract'), ('probation', 'Probation')], default='probation', verbose_name='Job Type')),
                ('joining_date', nepali_datetime_field.models.NepaliDateField(null=True, verbose_name='Joining Date')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_detail', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift', to='roster.shift')),
            ],
        ),
    ]
