# Generated by Django 5.1.7 on 2025-05-27 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('user', '0012_remove_profile_job_type_remove_profile_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingdetail',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='department.department'),
        ),
    ]
