# Generated by Django 5.1.7 on 2025-06-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_profile_profile_picture_alter_workingdetail_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingdetail',
            name='joining_date',
            field=models.DateField(null=True, verbose_name='Joining Date'),
        ),
    ]
