# Generated by Django 5.1.7 on 2025-06-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_workingdetail_joining_date'),
        ('user', '0015_document'),
    ]

    operations = [
    ]
