# Generated by Django 5.1.7 on 2025-06-16 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('user', '0016_merge_20250616_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingdetail',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch', to='branch.branch'),
        ),
    ]
