# Generated by Django 5.1.7 on 2025-06-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_merge_20250615_1702'),
        ('user', '0017_workingdetail_branch'),
    ]

    operations = [
    ]
