# Generated by Django 5.1.7 on 2025-06-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_merge_20250616_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='issue_body',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Issued By'),
        ),
        migrations.AddField(
            model_name='document',
            name='issue_date',
            field=models.DateField(null=True, verbose_name='Issue Date'),
        ),
    ]
