# Generated by Django 5.1.7 on 2025-06-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('cbs_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
