# Generated by Django 5.1.7 on 2025-06-20 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cbs_code', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='branch.province')),
            ],
        ),
    ]
