# Generated by Django 5.1.7 on 2025-06-17 14:08

import django.core.validators
import django.utils.timezone
import djgeojson.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('actual_checkin_time', models.TimeField(blank=True, null=True)),
                ('actual_checkout_time', models.TimeField(blank=True, null=True)),
                ('checkin_time', models.TimeField(blank=True, null=True)),
                ('checkout_time', models.TimeField(blank=True, null=True)),
                ('working_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('checkin_location', djgeojson.fields.PointField(blank=True, null=True)),
                ('checkout_location', djgeojson.fields.PointField(blank=True, null=True)),
                ('checkin_devices', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_devices', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('missed_checkout', 'Missed Checkout'), ('late_arrival_request', 'Late Arrival Request'), ('early_departure_request', 'Early Departure Request')], max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('forwarded', 'Forwarded'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
