# Generated by Django 5.1.7 on 2025-04-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='actual_checkin_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='actual_checkout_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('missed_checkout', 'Missed Checkout'), ('late_arrival_request', 'Late Arrival Request'), ('early_departure_request', 'Early Departure Request')], max_length=50),
        ),
    ]
