# Generated by Django 5.1.7 on 2025-06-03 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_actual_checkin_time_and_more'),
        ('roster', '0003_alter_roster_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='roster.shift'),
        ),
    ]
