# Generated by Django 5.1.7 on 2025-06-19 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_head',
            field=models.ManyToManyField(related_name='department_head', to=settings.AUTH_USER_MODEL),
        ),
    ]
